name: Run Hello Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite rodar manualmente o workflow

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Substitua pela versão do Python que você deseja usar

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instale dependências aqui, se necessário, por exemplo:
          # pip install -r requirements.txt

      - name: Run hello.py
        run: python3 hello.py
